apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: veganpro
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: veganpro
  targetCPUUtilizationPercentage: 70
