apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvcveganpro-nfs
  labels:
    app: pvcveganpro-nfs
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
