apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: veganpro
  namespace: vegan
rules:
  - apiGroups: [""]
    resources: ["pods","services","endpoints","namespaces","configmaps"]
    verbs: ["get","list","watch","create","delete","update"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: veganpro
  namespace: vegan

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: veganpro
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: veganpro
subjects:
- kind: ServiceAccount
  name: veganpro
  namespace: vegan
