apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vegan-pv
  labels:
    app: vegan-pv
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
