kind: PersistentVolume 
apiVersion: v1 
metadata: 
  name: postgres-pv-volume 
  labels: 
    type: local 
    app: postgres 
spec: 
  storageClassName: microk8s-hostpath 
  capacity: 
    storage: 5Gi 
  accessModes: 
    - ReadWriteMany 
  hostPath: 
    path: "/var/lib/postgre/data" 
--- 
kind: PersistentVolumeClaim 
apiVersion: v1 
metadata: 
  name: postgres-pv-claim 
  labels: 
     app: postgres 
spec: 
  storageClassName: microk8s-hostpath 
  accessModes: 
    - ReadWriteMany 
  resources: 
    requests: 
      storage: 5Gi 