#apiVersion: v1
#kind: ConfigMap
#metadata:
  #name: mysql-config
  #labels:
    #app: mysql
#data:
  #MYSQL_DB: postgresdb
  #MYSQL_USER: postgresadmin
  #MYSQL_PASSWORD: jinling
apiVersion: v1
#data:
  #my.cnf: "# but WITHOUT ANY WARRANTY; without even the implied warranty of
          # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
          # GNU General Public License, version 2.0, for more details.
          #
          # You should have received a copy of the GNU General Public License
          # along with this program; if not, write to the Free Software
          # Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA

          #!includedir /etc/mysql/conf.d/
          #!includedir /etc/mysql/mysql.conf.d/"
kind: ConfigMap
metadata:
  name: mysqldbconfigmap
  labels:
    app: postgres
data:
  MYSQL_DB: mysqldb
  MYSQL_USER: root
  MYSQL_ROOT_PASSWORD: jinling
