apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: mysql-deployment 
spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      app: mysql 
  template: 
    metadata: 
      labels: 
        app: mysql
    spec:
      containers:
        - image: mysql
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              #这是mysqlroot用户的密码
              valueFrom:
                secretKeyRef:
                  key: password
                  name: mysqldbsecret
          envFrom: 
            - configMapRef: 
                name: mysqldbconfigmap 
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysqldb
              mountPath: /var/lib/mysql
      volumes:
        - name: mysqldb
          persistentVolumeClaim:
            claimName: mysql-pv-claim

